-- Claude Pulse Team — Postgres schema v1
-- Companion: PRD.md, STACK.md, API.md
-- Target: Postgres 16+. UUIDv7 generated by clients (events) and server (other rows).
--
-- Conventions:
--   - All tenant-scoped tables include org_id + an index starting with org_id.
--   - `created_at` defaults to now(); `updated_at` set by application code.
--   - JSONB for free-form blobs (event payloads, redaction rules, audit metadata).
--   - Derived tables can be rebuilt from event_log; treat event_log as the source of truth.
-- ============================================================================

BEGIN;

-- ────────────────────────────────────────────────────────────────────────────
-- Extensions
-- ────────────────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "citext";     -- case-insensitive emails
CREATE EXTENSION IF NOT EXISTS "pg_trgm";    -- trigram indexes for insight search

-- ────────────────────────────────────────────────────────────────────────────
-- Enums
-- ────────────────────────────────────────────────────────────────────────────
CREATE TYPE plan_tier   AS ENUM ('free', 'studio', 'team', 'enterprise');
CREATE TYPE member_role AS ENUM ('owner', 'admin', 'lead', 'member');
CREATE TYPE member_status AS ENUM ('invited', 'active', 'stale', 'deactivated');
CREATE TYPE project_status AS ENUM ('active', 'archived');
CREATE TYPE redaction_mode AS ENUM ('off', 'standard', 'strict');
CREATE TYPE insight_type AS ENUM ('progress', 'decision', 'blocker', 'pattern', 'fix', 'context');
CREATE TYPE event_kind AS ENUM (
  'session.start', 'session.end',
  'prompt.submit',
  'tool.edit', 'tool.write', 'tool.read', 'tool.bash',
  'tool.glob', 'tool.grep', 'tool.agent', 'tool.skill',
  'tool.web_fetch', 'tool.web_search', 'tool.tool_search',
  'insight.progress', 'insight.decision', 'insight.blocker',
  'insight.pattern', 'insight.fix', 'insight.context',
  'blueprint.run',
  'heartbeat'
);
CREATE TYPE blueprint_status AS ENUM ('running', 'completed', 'failed');

-- ────────────────────────────────────────────────────────────────────────────
-- Tenancy: orgs, teams, members, redaction policies
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE orgs (
  id                            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                          TEXT NOT NULL,
  slug                          CITEXT NOT NULL UNIQUE,
  plan                          plan_tier NOT NULL DEFAULT 'free',
  billing_email                 CITEXT,
  retention_days                INTEGER NOT NULL DEFAULT 365,
  default_redaction_policy_id   UUID,
  created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE teams (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id      UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (org_id, name)
);
CREATE INDEX teams_org_idx ON teams (org_id);

CREATE TABLE members (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  team_id         UUID REFERENCES teams(id) ON DELETE SET NULL,
  email           CITEXT NOT NULL,
  name            TEXT,
  role            member_role NOT NULL DEFAULT 'member',
  status          member_status NOT NULL DEFAULT 'invited',
  oauth_provider  TEXT,
  oauth_subject   TEXT,
  invited_by      UUID REFERENCES members(id) ON DELETE SET NULL,
  invited_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  activated_at    TIMESTAMPTZ,
  deactivated_at  TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (org_id, email),
  UNIQUE (oauth_provider, oauth_subject)
);
CREATE INDEX members_org_status_idx ON members (org_id, status);

CREATE TABLE redaction_policies (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  mode            redaction_mode NOT NULL DEFAULT 'standard',
  drop_diffs      BOOLEAN NOT NULL DEFAULT TRUE,
  hash_file_paths BOOLEAN NOT NULL DEFAULT FALSE,
  drop_prompts    BOOLEAN NOT NULL DEFAULT TRUE,
  regex_redactions JSONB NOT NULL DEFAULT '[]'::jsonb,
  max_payload_bytes INTEGER NOT NULL DEFAULT 65536,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (org_id, name)
);
CREATE INDEX redaction_policies_org_idx ON redaction_policies (org_id);

ALTER TABLE orgs
  ADD CONSTRAINT orgs_default_policy_fk
  FOREIGN KEY (default_redaction_policy_id)
  REFERENCES redaction_policies(id) ON DELETE SET NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- Projects + access control
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE projects (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id              UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  team_id             UUID REFERENCES teams(id) ON DELETE SET NULL,
  canonical_key       TEXT NOT NULL,
  name                TEXT NOT NULL,
  vcs_provider        TEXT,
  vcs_repo_id         TEXT,
  remote_url          TEXT,
  redaction_policy_id UUID REFERENCES redaction_policies(id) ON DELETE SET NULL,
  status              project_status NOT NULL DEFAULT 'active',
  needs_review        BOOLEAN NOT NULL DEFAULT TRUE,
  created_by          UUID REFERENCES members(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  archived_at         TIMESTAMPTZ,
  UNIQUE (org_id, canonical_key)
);
CREATE INDEX projects_org_status_idx ON projects (org_id, status);
CREATE INDEX projects_org_needs_review_idx ON projects (org_id) WHERE needs_review;

CREATE TABLE member_project_access (
  member_id   UUID NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  role        member_role NOT NULL DEFAULT 'member',
  granted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  granted_by  UUID REFERENCES members(id) ON DELETE SET NULL,
  PRIMARY KEY (member_id, project_id)
);
CREATE INDEX mpa_project_idx ON member_project_access (project_id);

-- ────────────────────────────────────────────────────────────────────────────
-- API keys (workstation auth)
-- Stored hashed via HMAC-SHA-256 with a server-side pepper. last4 is plaintext for display.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE api_keys (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  member_id       UUID NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  label           TEXT,
  key_hash        BYTEA NOT NULL,
  key_last4       TEXT NOT NULL,
  last_used_at    TIMESTAMPTZ,
  last_seen_meta  JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at      TIMESTAMPTZ,
  UNIQUE (key_hash)
);
CREATE INDEX api_keys_member_idx ON api_keys (member_id) WHERE revoked_at IS NULL;
CREATE INDEX api_keys_org_idx ON api_keys (org_id) WHERE revoked_at IS NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- Dashboard sessions (Lucia-style)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE dashboard_sessions (
  id          TEXT PRIMARY KEY,
  member_id   UUID NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  org_id      UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  ip          INET,
  user_agent  TEXT
);
CREATE INDEX dashboard_sessions_member_idx ON dashboard_sessions (member_id);
CREATE INDEX dashboard_sessions_expiry_idx ON dashboard_sessions (expires_at);

-- ────────────────────────────────────────────────────────────────────────────
-- Event log — immutable, append-only, source of truth.
-- All derived tables (sessions, tool_events, insights, blueprint_runs,
-- daily_summaries, file_activity) are rebuildable from this table alone.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE event_log (
  id              UUID PRIMARY KEY,                 -- client-generated UUIDv7
  org_id          UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  member_id       UUID NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  project_id      UUID NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  session_id      UUID,
  event_kind      event_kind NOT NULL,
  payload         JSONB NOT NULL,                   -- post-redaction payload
  client_meta     JSONB NOT NULL DEFAULT '{}'::jsonb, -- hook_version, os, cloud_env, hostname
  hook_ts         TIMESTAMPTZ NOT NULL,
  received_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  redaction_applied JSONB NOT NULL DEFAULT '{}'::jsonb,
  api_key_id      UUID REFERENCES api_keys(id) ON DELETE SET NULL
);
CREATE INDEX event_log_org_received_idx ON event_log (org_id, received_at DESC);
CREATE INDEX event_log_org_project_received_idx ON event_log (org_id, project_id, received_at DESC);
CREATE INDEX event_log_org_member_received_idx ON event_log (org_id, member_id, received_at DESC);
CREATE INDEX event_log_session_idx ON event_log (session_id) WHERE session_id IS NOT NULL;
CREATE INDEX event_log_kind_idx ON event_log (org_id, event_kind, received_at DESC);

-- Note: at scale, partition event_log BY RANGE (received_at) monthly.
-- Defer until we cross ~50M rows.

-- ────────────────────────────────────────────────────────────────────────────
-- Derived: sessions
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE sessions (
  id                UUID PRIMARY KEY,
  org_id            UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  member_id         UUID NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  project_id        UUID NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  started_at        TIMESTAMPTZ NOT NULL,
  ended_at          TIMESTAMPTZ,
  duration_seconds  INTEGER,
  summary           TEXT,
  status            TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed','crashed')),
  hostname          TEXT,
  cloud_env         TEXT,
  hook_version      TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX sessions_org_started_idx ON sessions (org_id, started_at DESC);
CREATE INDEX sessions_org_project_started_idx ON sessions (org_id, project_id, started_at DESC);
CREATE INDEX sessions_org_member_started_idx ON sessions (org_id, member_id, started_at DESC);
CREATE INDEX sessions_org_status_idx ON sessions (org_id, status);

-- ────────────────────────────────────────────────────────────────────────────
-- Derived: tool_events
-- One row per tool invocation (Edit, Write, Bash, Read, Glob, Grep, Agent, Skill, …).
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE tool_events (
  id                  UUID PRIMARY KEY,
  org_id              UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  session_id          UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  member_id           UUID NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  project_id          UUID NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  tool_name           TEXT NOT NULL,
  ts                  TIMESTAMPTZ NOT NULL,
  file_path           TEXT,
  language            TEXT,
  lines_added         INTEGER NOT NULL DEFAULT 0,
  lines_removed       INTEGER NOT NULL DEFAULT 0,
  command             TEXT,
  detected_framework  TEXT,
  command_failed      BOOLEAN NOT NULL DEFAULT FALSE,
  search_pattern      TEXT,
  agent_type          TEXT,
  agent_description   TEXT,
  skill_name          TEXT,
  skill_args          TEXT,
  diff_excerpt        TEXT,
  metadata            JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX tool_events_session_idx ON tool_events (session_id, ts);
CREATE INDEX tool_events_org_ts_idx ON tool_events (org_id, ts DESC);
CREATE INDEX tool_events_org_project_ts_idx ON tool_events (org_id, project_id, ts DESC);
CREATE INDEX tool_events_org_tool_idx ON tool_events (org_id, tool_name, ts DESC);
CREATE INDEX tool_events_file_idx ON tool_events (project_id, file_path) WHERE file_path IS NOT NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- Derived: insights (decisions, blockers, progress, patterns, fixes, context)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE insights (
  id          UUID PRIMARY KEY,
  org_id      UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  session_id  UUID REFERENCES sessions(id) ON DELETE SET NULL,
  member_id   UUID NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  type        insight_type NOT NULL,
  title       TEXT,
  content     TEXT NOT NULL,
  reasoning   TEXT,
  resolved_at TIMESTAMPTZ,             -- only meaningful for blockers
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX insights_org_created_idx ON insights (org_id, created_at DESC);
CREATE INDEX insights_org_project_created_idx ON insights (org_id, project_id, created_at DESC);
CREATE INDEX insights_org_member_created_idx ON insights (org_id, member_id, created_at DESC);
CREATE INDEX insights_org_type_idx ON insights (org_id, type, created_at DESC);
CREATE INDEX insights_blockers_open_idx ON insights (org_id, project_id) WHERE type = 'blocker' AND resolved_at IS NULL;
CREATE INDEX insights_content_trgm_idx ON insights USING GIN (content gin_trgm_ops);
CREATE INDEX insights_title_trgm_idx ON insights USING GIN (title gin_trgm_ops);

-- ────────────────────────────────────────────────────────────────────────────
-- Derived: blueprint_runs
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE blueprint_runs (
  id              UUID PRIMARY KEY,
  org_id          UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  member_id       UUID NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  project_id      UUID NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  session_id      UUID REFERENCES sessions(id) ON DELETE SET NULL,
  blueprint       TEXT NOT NULL,
  input           TEXT,
  status          blueprint_status NOT NULL,
  started_at      TIMESTAMPTZ NOT NULL,
  completed_at    TIMESTAMPTZ,
  duration_ms     INTEGER,
  step_count      INTEGER NOT NULL DEFAULT 0,
  steps_done      INTEGER NOT NULL DEFAULT 0,
  steps_failed    INTEGER NOT NULL DEFAULT 0,
  step_results    JSONB NOT NULL DEFAULT '[]'::jsonb,
  worktree_path   TEXT,
  worktree_branch TEXT,
  base_branch     TEXT,
  source_file     TEXT,
  source_mtime    BIGINT,
  ingested_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX blueprint_runs_org_started_idx ON blueprint_runs (org_id, started_at DESC);
CREATE INDEX blueprint_runs_project_idx ON blueprint_runs (org_id, project_id, started_at DESC);
CREATE INDEX blueprint_runs_status_idx ON blueprint_runs (org_id, status, started_at DESC);
CREATE INDEX blueprint_runs_session_idx ON blueprint_runs (session_id) WHERE session_id IS NOT NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- Derived: file_activity (per-file rollup, per day)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE file_activity (
  id            BIGSERIAL PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  project_id    UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  file_path     TEXT NOT NULL,
  date          DATE NOT NULL,
  edit_count    INTEGER NOT NULL DEFAULT 0,
  write_count   INTEGER NOT NULL DEFAULT 0,
  read_count    INTEGER NOT NULL DEFAULT 0,
  lines_added   INTEGER NOT NULL DEFAULT 0,
  lines_removed INTEGER NOT NULL DEFAULT 0,
  language      TEXT,
  UNIQUE (project_id, file_path, date)
);
CREATE INDEX file_activity_org_date_idx ON file_activity (org_id, date DESC);
CREATE INDEX file_activity_project_date_idx ON file_activity (project_id, date DESC);
CREATE INDEX file_activity_hotspot_idx ON file_activity (project_id, edit_count DESC, date DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- Derived: daily_summaries (per-project rollup, per day)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE daily_summaries (
  id                      BIGSERIAL PRIMARY KEY,
  org_id                  UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  project_id              UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  date                    DATE NOT NULL,
  session_count           INTEGER NOT NULL DEFAULT 0,
  total_duration_seconds  INTEGER NOT NULL DEFAULT 0,
  lines_added             INTEGER NOT NULL DEFAULT 0,
  lines_removed           INTEGER NOT NULL DEFAULT 0,
  net_lines               INTEGER NOT NULL DEFAULT 0,
  files_created           INTEGER NOT NULL DEFAULT 0,
  files_edited            INTEGER NOT NULL DEFAULT 0,
  files_read              INTEGER NOT NULL DEFAULT 0,
  tool_calls              INTEGER NOT NULL DEFAULT 0,
  bash_commands           INTEGER NOT NULL DEFAULT 0,
  bash_failures           INTEGER NOT NULL DEFAULT 0,
  searches                INTEGER NOT NULL DEFAULT 0,
  agents_spawned          INTEGER NOT NULL DEFAULT 0,
  decisions               INTEGER NOT NULL DEFAULT 0,
  blockers_opened         INTEGER NOT NULL DEFAULT 0,
  blockers_resolved       INTEGER NOT NULL DEFAULT 0,
  active_member_ids       UUID[] NOT NULL DEFAULT '{}'::uuid[],
  skills_used             JSONB NOT NULL DEFAULT '{}'::jsonb,
  frameworks_detected     JSONB NOT NULL DEFAULT '{}'::jsonb,
  languages               JSONB NOT NULL DEFAULT '{}'::jsonb,
  tool_counts             JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (project_id, date)
);
CREATE INDEX daily_summaries_org_date_idx ON daily_summaries (org_id, date DESC);
CREATE INDEX daily_summaries_project_date_idx ON daily_summaries (project_id, date DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- Heartbeats (one row per workstation, latest wins)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE heartbeats (
  api_key_id      UUID PRIMARY KEY REFERENCES api_keys(id) ON DELETE CASCADE,
  org_id          UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  member_id       UUID NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  hostname        TEXT,
  cloud_env       TEXT,
  hook_version    TEXT,
  outbox_depth    INTEGER NOT NULL DEFAULT 0,
  last_event_id   UUID,
  last_event_ts   TIMESTAMPTZ,
  last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX heartbeats_org_last_seen_idx ON heartbeats (org_id, last_seen_at DESC);
CREATE INDEX heartbeats_member_idx ON heartbeats (member_id);
-- Stale-workstation lookups: filter `last_seen_at < now() - INTERVAL '6 hours'`
-- at query time. Partial indexes with `now()` aren't legal (now() is STABLE,
-- not IMMUTABLE), so we keep this as a regular two-column index.
CREATE INDEX heartbeats_org_last_seen_full_idx ON heartbeats (org_id, last_seen_at);

-- ────────────────────────────────────────────────────────────────────────────
-- Audit log (admin actions, immutable)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE audit_log (
  id              BIGSERIAL PRIMARY KEY,
  org_id          UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  actor_member_id UUID REFERENCES members(id) ON DELETE SET NULL,
  action          TEXT NOT NULL,                  -- e.g. 'project.bind', 'member.invite', 'api_key.revoke'
  target_type     TEXT,
  target_id       TEXT,
  payload         JSONB NOT NULL DEFAULT '{}'::jsonb,
  ip              INET,
  user_agent      TEXT,
  ts              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_org_ts_idx ON audit_log (org_id, ts DESC);
CREATE INDEX audit_log_org_actor_ts_idx ON audit_log (org_id, actor_member_id, ts DESC);
CREATE INDEX audit_log_org_action_ts_idx ON audit_log (org_id, action, ts DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- Dead letter queue — events that failed processing repeatedly
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE dead_letter_events (
  id              BIGSERIAL PRIMARY KEY,
  org_id          UUID REFERENCES orgs(id) ON DELETE CASCADE,
  api_key_id      UUID REFERENCES api_keys(id) ON DELETE SET NULL,
  event_id        UUID,
  payload         JSONB NOT NULL,
  reason          TEXT NOT NULL,
  retry_count     INTEGER NOT NULL DEFAULT 0,
  last_error      TEXT,
  received_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at     TIMESTAMPTZ
);
CREATE INDEX dle_org_received_idx ON dead_letter_events (org_id, received_at DESC) WHERE resolved_at IS NULL;
CREATE INDEX dle_event_idx ON dead_letter_events (event_id) WHERE event_id IS NOT NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- Triggers: keep updated_at fresh
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER orgs_updated     BEFORE UPDATE ON orgs               FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER members_updated  BEFORE UPDATE ON members            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER policies_updated BEFORE UPDATE ON redaction_policies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER projects_updated BEFORE UPDATE ON projects           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER sessions_updated BEFORE UPDATE ON sessions           FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ────────────────────────────────────────────────────────────────────────────
-- End of schema v1
-- ────────────────────────────────────────────────────────────────────────────

COMMIT;
